### PR TITLE
Add support for twitter video embeds.

### PR DESCRIPTION
**Pull request by mikelax**
Addresses issue #24

### CODE REVIEW

**Comment by orrybaram** [comment]
@iefserge and @kesla can chime in here, but I think we're sticking with deku ^1.0.0 for now, which is why you might have been getting these element errors.

**Comment by nazar** [comment]
hey @orrybaram - not sure why the tests failed specifically on node 4 only. `npm test` passed on my host (v4.4.3) and also on travis for node 4 and 0.10

**Comment by nazar** [comment]
> but I think we're sticking with deku ^1.0.0 for now,

`deku ^1.0.0` was under `devDependencies` and I added `"deku": "^2.0.0-rc16"` under `dependencies` to match the deku version in [article-json-to-fbia](https://github.com/micnews/article-json-to-fbia/blob/master/package.json#L42) (as that package had issues when deku attempted to render `virtual-element` elements) where I notice that the embeds package is held back to [^1.4.2](https://github.com/micnews/article-json-to-fbia/blob/master/package.json#L43).

I ran `npm test` under v4.4.5 (to match travis) on my dev and all tests pass. Would it be possible to re-run the travis tests again? I had a quick look but was not able to.

**Comment by nazar** [comment]
This PR is required by [html-to-article-json#58](https://github.com/micnews/html-to-article-json/pull/58) and [article-json-to-fbia#4](https://github.com/micnews/article-json-to-fbia/pull/4)

**Comment by nazar** [comment]
Hey @iefserge and @kesla,

Any updates on the status of this PR? I'd be more than happy to offer any clarifications or further commits to address any concerns you might have.

Thanks!

**Comment by iefserge** [comment]
@nazar I agree, I think we should keep using deku@1 for now. We can upgrade later to the stable deku@2 when available, but it's going to be a major release.

**Comment by nazar** [comment]
Thanks for the update @iefserge - as far as I can tell, doku@1 is only required for the tests.

The bigger issue I think is the removal of `virtual-element` which didn't work when embeds@2 is being used by `article-json-to-fbia` which itself uses deku@2 but an older version of embeds@^1.4.2

Should we have branched off embeds@1.5.0 instead for adding the twitter-video support for `article-json-to-fbia`? I'll also try and revert back to deku@1

**Comment by kesla** [comment]
Hey,

We should merge https://github.com/micnews/article-json-to-fbia/pull/2 to move article-json-to-fbia to deku@1 then we can merge this as well (with deku@1 support).

@nazar sorry for the confusion

**Comment by nazar** [comment]
Thanks @kesla - that makes a lot of sense now :D - I'm moving this to deku@1

**Comment by nazar** [comment]
Hey @kesla - reverted to use deku@1 and `magic-virtual-element`

**Comment by kesla** [comment]
@nazar ty

**Comment by kesla** [comment]
@nazar released in 2.5.0!

**Comment by mikelax** [comment]
Thanks a lot @kesla.

**Comment by kesla** [comment]
@mikelax No, thank you. This is a feature that we'll definitely will have good use of ourselves!

**Pull request merged**
